<a href="https://colab.research.google.com/github/verma-satyam/ML-Coding-Ninjas/blob/main/8.%20Naive%20Bayes/2_GaussianNB_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Dataset

In [1]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
Y = iris.target

## Model Trainig and Predictions

In [2]:
import numpy as np

Naive Bayes Classifier on continuous data - using Gaussian Curve

In [3]:
from sklearn import model_selection
X_train,X_test,Y_train,Y_test = model_selection.train_test_split(X,Y,test_size = 0.25, random_state=0)

In [4]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
result = clf.fit(X_train,Y_train)
Y_pred = clf.predict(X_test)

In [5]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         9

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
