<a href="https://colab.research.google.com/github/verma-satyam/ML-Coding-Ninjas/blob/main/8.%20Naive%20Bayes/3_MultinomialNB_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Dataset

In [1]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
Y = iris.target

## Model Trainig and Predictions

In [2]:
import numpy as np

Naive Bayes Classifier on continuous data - using Gaussian Curve

In [3]:
from sklearn import model_selection
X_train,X_test,Y_train,Y_test = model_selection.train_test_split(X,Y,test_size = 0.25, random_state=0)

In [4]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
result = clf.fit(X_train,Y_train)
Y_pred = clf.predict(X_test)

In [5]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.00      0.00      0.00        16
           2       0.36      1.00      0.53         9

    accuracy                           0.58        38
   macro avg       0.45      0.67      0.51        38
weighted avg       0.43      0.58      0.47        38

[[13  0  0]
 [ 0  0 16]
 [ 0  0  9]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**very bad bcz multinomial NB is used for text classification ,i.e, where dataset is of vocabulary type and is not workable on dataset like iris.**