<a href="https://colab.research.google.com/github/verma-satyam/ML-Coding-Ninjas/blob/main/16.%20Tensorflow/1_TensorFlow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

### Constants

In [3]:
a = tf.constant(2)
b = tf.constant(3)
c = a+b
a,b,c

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>)

In [4]:
a1 = tf.constant([[3,3]])
a2 = tf.constant([[3],[3]])
res = tf.matmul(a1,a2)
a1,a2,res

(<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[3],
        [3]], dtype=int32)>,
 <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[18]], dtype=int32)>)

In [7]:
# sess = tf.Session()
# sess.run(c),sess.run(res)
# session is no longer used in tf now. simple python comands
tf.print(c,res)

5 [[18]]


### Session

In [ ]:
with tf.Session() as sess:
  print(c.eval())
  print(res.eval())

# this doesn't work anymore.
# else use down block.

In [11]:
c.numpy(),res.numpy()

(5, array([[18]], dtype=int32))

### Variables

In [12]:
var1 = tf.Variable(100)
var2 = tf.Variable(3)
sum = tf.add(var1,var2)
sum,var1,var2

(<tf.Tensor: shape=(), dtype=int32, numpy=103>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>)

In [13]:
tf.print(sum)

103


In [14]:
var1.assign(1232)
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1232>

### Placeholder

In [16]:
# x = tf.placeholder(tf.int32)
# y = x * tf.constant(12)
# sess.run(y,feed_dict={x:[[1,2,3],[4,5,6]]})
# placeholders are no longer available

AttributeError: ignored

In [19]:
@tf.function
def y(x):
  return x * tf.constant(12)

out_a = y([[1,2,3],[4,5,6]])
print(out_a)
## instead of placeholders we'll make functions

tf.Tensor(
[[12 24 36]
 [48 60 72]], shape=(2, 3), dtype=int32)
