<a href="https://colab.research.google.com/github/verma-satyam/ML-Coding-Ninjas/blob/main/9.%20KNN/1_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split,cross_val_score,KFold
from sklearn.linear_model import LinearRegression

In [2]:
iris = datasets.load_iris()
X_train,X_test,Y_train,Y_test = train_test_split(iris.data,iris.target,test_size=0.2,random_state=0)

In [3]:
clf = LinearRegression()
# 5 fold cross validation
cross_val_score(clf,X_train,Y_train)

array([0.88027523, 0.87653834, 0.97263486, 0.96003738, 0.90267142])

In [4]:
# cross validation on whole dataset
cross_val_score(clf,iris.data,iris.target)

array([0.        , 0.85124923, 0.        , 0.76155439, 0.        ])

In [5]:
# 3 fold cross validation
# KFold(number of splits,random Splits??, random state)
cross_val_score(clf,X_train,Y_train,cv=KFold(3,True,0))

array([0.91405112, 0.94558204, 0.91367333])